-- 코드를 작성해주세요-
WITH MAX_SIZE_FOR_YEAR(YEAR, MAX_SIZE) AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) YEAR, MSFY.MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS ED
JOIN MAX_SIZE_FOR_YEAR AS MSFY
ON YEAR(ED.DIFFERENTIATION_DATE) = MSFY.YEAR
ORDER BY YEAR, YEAR_DEV