-- 코드를 입력하세요
SELECT 
    TITLE,
    BOARD_ID,
    R.REPLY_ID,
    R.WRITER_ID,
    R.CONTENTS,
    DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
INNER JOIN USED_GOODS_REPLY R
USING(BOARD_ID)
where date_format(B.CREATED_DATE,'%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE, TITLE